### ISSUE TITLE
ndb

### ISSUE THREAD

**Issue by paulirish** [Wandalen/DebugNode#11]
Heya!

I don't entirely understand this project's goals, but I wanted to make sure you know about ndb: https://github.com/GoogleChromeLabs/ndb/

It's all about easily debugging node using the DevTools frontend.

Anyway.. sorry for randomly dropping an issue! :)

**Comment by Wandalen** [comment]
Yeah we are aware.. but ndb is buggy and sub-optimal.. 
At least at the moment.

**Comment by paulirish** [comment]
Okay no problem! Thanks. :)
